line.bot:
  channel-token: '3305RotPKhkmy6Q/BOpKIfgiEU852QFhqbJsSuQviMAd6ZqVGTHY2qpEnQnyP4PXW7/9AgUCavV9an4fwW+vCG1t6xIAEtEtnc8yZD3HuAoac7qlQvrN7soXP/jaJUjq4TYcJXFW/wv0Xavqb9LmOQdB04t89/1O/w1cDnyilFU='
  channel-secret: 'e2adf461b13da7d64e111252292ae904'
  handler.path: /callback
