line.bot:
  channel-token: 'kopv00zsh1KZbs20uTR+cOMW2wb/LPWylRfxr80PGOHCter0H99V+jYzuFqHLQw/W7/9AgUCavV9an4fwW+vCG1t6xIAEtEtnc8yZD3HuAqcl4DcOVeRSnpdXTX9MfqKBh9TAtOuyGjChj3KtyP4FAdB04t89/1O/w1cDnyilFU='
  channel-secret: 'e2adf461b13da7d64e111252292ae904'
  handler.path: /callback
